name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: [ '2.3.8', '2.4.10', '2.5.8', '2.6.6' ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: gem install bundler -v 1.17.3
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rspec
